graph TD
  A(Database search) -.->|Export to text file| R[Search results]
  R --> D(Check search results)
  D -->|Count records| D1[Record count]
  D1 --> I
  D -->|Count non-duplicates| D2[Single-database duplicate count]
  D2 --> I
  R ----->|Combine export files| E[Single import file]
  R -->|Extract| F[Set of accession numbers]
  F -->|Generate query| Q[Query string for known records]
  F ----> I
  Q --> U("Deduplication in update search (NOT)")
  U --> A
  A(Database search) -.->|Export to text file| S[Search strategy]
  S ---->|Reformat| I[Documentation]
  classDef Result fill:#ffffde,stroke:#aaaa33,stroke-width:4px;
  class A,I,E Result;

